### ISSUE TITLE
Strange error coming when I deploy demo app on android emulator

### ISSUE THREAD

**Issue by ghost** [nishanil/YouTubeAndroidPlayer#4]
I tried to use this app in emulator but this is not working. I see errors like this 

The project YouTubeDemo needs to be deployed before it can be started. Verify the project is selected to be deployed in the Solution Configuration Manager.

I tried to use 5.0 , 7.1 and 8.0 android but this things not work. I have tried with deploy than debug but still same error.

Any idea,  what can be issue @nishanil 

Thanks you your useful repository.

**Comment by nishanil** [comment]
YouTube app must be installed first.
